detail/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'detail'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("<int:detail_id>", views.detailproduk, name='detailproduk')
    # yon yang detail produk tambahin id ya buat nge link ke produk tertentu yang dia mau
]
#landing pagenya ke list produk, ngambl dr models yg ada di list produk buat detail sm testi

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

keranjang/urls.py
from django.urls import path
from . import views

app_name = 'keranjang'

urlpatterns = [
    path('', views.keranjang, name='keranjang'),
    path('checkout', views.checkout, name='checkout'),
    path('add/<int:detail_id>', views.addToKeranjang, name='tambah'),
    path('addPOST', views.addPOST, name='addPOST'),
    path('delPOST', views.delPOST, name='delPOST'),
    path('incPOST', views.incPOST, name='incPOST'),
    path('decPOST', views.decPOST, name='decPOST'),
]

produk/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'produk'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.listproduk, name='listproduk'),
    path("addproduk/", views.addproduk, name='addproduk'),
    # path("detailproduct/<int:detail_id>", views.detailproduk, name='detailproduk')
    # yon yang detail produk tambahin id ya buat nge link ke produk tertentu yang dia mau
]
#landing pagenya ke list produk, ngambl dr models yg ada di list produk buat detail sm testi

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('listproduk/', include('produk.urls')),
    path('keranjang/', include('keranjang.urls')),
    path('bantuan/', include('bantuan.urls')),
    path('detail/', include('detail.urls')),
]

handler404 = views.handler404
handler500 = views.handler500

keranjang/models.py
from django.db import models
from produk.models import AddProduk
import uuid

class Visitor(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    def __str__(self):
        return "{}".format(self.id)

class ProdukDiKeranjang(models.Model):
    product = models.ForeignKey(AddProduk, on_delete=models.CASCADE)
    visitor = models.ForeignKey(Visitor, on_delete=models.CASCADE, related_name='produkdikeranjang')
    jumlah = models.PositiveIntegerField()
    
    def __str__(self):
        return f'{self.product.nama} di {self.visitor}'

class PaymentMethod(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Courier(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class StatusPengiriman(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class DetailPengiriman(models.Model):
    nama = models.CharField(max_length=30)
    telpon = models.CharField(max_length=15)
    email = models.EmailField()
    alamat = models.CharField(max_length=100)
    total_harga = models.PositiveIntegerField()
    waktu_checkout = models.DateTimeField(auto_now_add=True)
    kurir = models.ForeignKey(Courier, on_delete=models.SET_NULL, null=True)
    metode_pembayaran = models.ForeignKey(PaymentMethod, on_delete=models.SET_NULL, null=True)
    status_pengiriman = models.ForeignKey(StatusPengiriman, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.nama} pada {self.waktu_checkout}'

class ProdukAkanDikirim(models.Model):
    product = models.ForeignKey(AddProduk, on_delete=models.RESTRICT, related_name='produkakandikirim')
    detailpengiriman = models.ForeignKey(DetailPengiriman, on_delete=models.CASCADE, related_name='produkakandikirim')
    jumlah = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.detailpengiriman.nama} pada {self.detailpengiriman.waktu_checkout}'

keranjang/forms.py
from django import forms
from .models import DetailPengiriman, PaymentMethod, Courier

class FormPengiriman(forms.Form) :
    nama = forms.CharField(
        label = 'Nama Lengkap',
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'Nama Lengkap Anda',
            'type' : 'text',
            'required' : True, 
            'style': 'margin-bottom: 10px;'
    }))

    telpon = forms.CharField(
        label = 'Nomor Telepon',
        widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : '081234567890',
            'type' : 'text',
            'required' : True,
            'style': 'margin-bottom: 10px;'
        })
    )

    email = forms.EmailField(
        label = 'Email',
        widget=forms.EmailInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'emailanda@gmail.com',
            'type' : 'text',
            'required' : True,
            'style': 'margin-bottom: 10px;'
        
    }))

    metode_pembayaran = forms.ModelChoiceField(
        label= 'Metode Pembayaran',
        queryset=PaymentMethod.objects.all(),
        widget=forms.Select(attrs={
            'class' : 'form-control',
            'required' : True,
            'style': 'margin-bottom: 10px;'
    }))

    kurir = forms.ModelChoiceField(
        label= 'Pilih Kurir',
        queryset=Courier.objects.all(),
        widget=forms.Select(attrs={
            'class' : 'form-control',
            'required' : True,
            'style': 'margin-bottom: 10px;'
    }))
    

    alamat = forms.CharField(
        label = 'Alamat Lengkap',
        widget=forms.Textarea(attrs={
            'class' : 'form-control',
            'placeholder' : 'Alamat Lengkap',
            'type' : 'text',
            'required' : True,
            'style': 'margin-bottom: 10px;'
    }))

keranjang/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.db import IntegrityError
from produk.models import AddProduk
from .models import ProdukDiKeranjang, DetailPengiriman, Visitor, ProdukAkanDikirim, PaymentMethod, Courier, StatusPengiriman
from .forms import FormPengiriman
import datetime
import uuid

def keranjang(request):
    visitor = getVisitor(request)

    produk = ProdukDiKeranjang.objects.filter(visitor=visitor)
    form = FormPengiriman()
    
    totalHarga = sum([(x.product.harga * x.jumlah) for x in produk])
    
    response = {
        'produk' : produk,
        'form' : form,
        'totalHarga' : totalHarga,
        'hide_nav_2' : True,
        'hide_footer': True,
    }
    return render(request, 'keranjang/keranjang.html', response)

def checkout(request):
    visitor = getVisitor(request)

    if request.method=='POST':

        if ProdukDiKeranjang.objects.filter(visitor=visitor).count() != 0:

            produk_di_keranjang = ProdukDiKeranjang.objects.filter(visitor=visitor)
            totalHarga = sum([(x.product.harga * x.jumlah) for x in produk_di_keranjang])
            formCheckout = FormPengiriman(request.POST or None)

            if formCheckout.is_valid():

                detailpengiriman = DetailPengiriman.objects.create(
                    nama = formCheckout.cleaned_data['nama'],
                    telpon = formCheckout.cleaned_data['telpon'],
                    email = formCheckout.cleaned_data['email'],
                    alamat = formCheckout.cleaned_data['alamat'],
                    total_harga = totalHarga,
                    kurir = Courier.objects.get(name=formCheckout.cleaned_data['kurir']),
                    metode_pembayaran = PaymentMethod.objects.get(name=formCheckout.cleaned_data['metode_pembayaran']),
                    status_pengiriman = StatusPengiriman.objects.get(name='Menunggu Pembayaran')
                )

                for p in produk_di_keranjang:
                    ProdukAkanDikirim.objects.create(
                        product = p.product,
                        detailpengiriman = detailpengiriman,
                        jumlah = p.jumlah
                    )

                    produk = AddProduk.objects.get(id=p.product.id)
                    produk.stok -= p.jumlah
                    produk.save()

                produk_di_keranjang.delete()
                response = {
                    'detail' : detailpengiriman,
                    'hide_nav_2' : True,
                    'hide_footer': True,
                }


                return render(request, 'keranjang/checkout.html', response)
        else:
            return HttpResponseBadRequest('ProdukDiKeranjang instance not found')
    else:
        return redirect('keranjang:keranjang')

def addToKeranjang(request, detail_id):
    try:
        produk = AddProduk.objects.get(id=detail_id)
        visitor = getVisitor(request)

        if len(ProdukDiKeranjang.objects.filter(product=produk, visitor=visitor)) == 0:
            ProdukDiKeranjang.objects.create(
                product = produk,
                visitor = visitor,
                jumlah = 1,
            )
            
        return redirect('keranjang:keranjang')
    except AddProduk.DoesNotExist:
        return HttpResponseBadRequest('Produk instance not found')

def addPOST(request):
    if request.method == 'POST':
        try:
            detail_id = request.POST.get('detail_id')
            produk = AddProduk.objects.get(id=detail_id)
            visitor = getVisitor(request)

            if len(ProdukDiKeranjang.objects.filter(product=produk, visitor=visitor)) == 0:
                ProdukDiKeranjang.objects.create(
                    product = produk,
                    visitor = visitor,
                    jumlah = 1,
                )
            
            return redirect('keranjang:keranjang')

        except AddProduk.DoesNotExist:
            return HttpResponseBadRequest('Produk instance not found')
    
    else:
        return HttpResponseBadRequest('GET method is not allowed')

def delPOST(request):
    if request.method == 'POST':
        try:
            detail_id = request.POST.get('detail_id')
            produk = AddProduk.objects.get(id=detail_id)
            visitor = getVisitor(request)

            ProdukDiKeranjang.objects.get(product=produk, visitor=visitor).delete()
            return redirect('keranjang:keranjang')

        except ProdukDiKeranjang.DoesNotExist:
            return HttpResponseBadRequest('ProdukDiKeranjang instance not found')
        
        except AddProduk.DoesNotExist:
            return HttpResponseBadRequest('AddProduk instance not found')

    else:
        return HttpResponseBadRequest('GET method is not allowed')
       
def incPOST(request):
    if request.method == 'POST':
        try:
            detail_id = request.POST.get('detail_id')
            produk = AddProduk.objects.get(id=detail_id)
            visitor = getVisitor(request)

            produk_di_keranjang = ProdukDiKeranjang.objects.get(product=produk, visitor=visitor)

            if produk_di_keranjang.jumlah == produk.stok:
                return HttpResponseBadRequest('ProdukDiKeranjang.jumlah cannot exceeds stok produk')

            else:
                produk_di_keranjang.jumlah += 1
                produk_di_keranjang.save()
                return redirect('keranjang:keranjang')

        except ProdukDiKeranjang.DoesNotExist:
            return HttpResponseBadRequest('ProdukDiKeranjang instance not found')

        except AddProduk.DoesNotExist:
            return HttpResponseBadRequest('AddProduk instance not found')

    else:
        return HttpResponseBadRequest('GET method is not allowed')

def decPOST(request):
    if request.method=='POST':
        try:
            detail_id = request.POST.get('detail_id')
            produk = AddProduk.objects.get(id=detail_id)
            visitor = getVisitor(request)

            produk_di_keranjang = ProdukDiKeranjang.objects.get(product=produk, visitor=visitor)

            if produk_di_keranjang.jumlah == 1:
                return HttpResponseBadRequest('ProdukDiKeranjang.jumlah cannot be zero')

            else:
                produk_di_keranjang.jumlah -= 1
                produk_di_keranjang.save()
                return redirect('keranjang:keranjang')

        except ProdukDiKeranjang.DoesNotExist:
            return HttpResponseBadRequest('ProdukDiKeranjang instance not found') 

        except AddProduk.DoesNotExist:
            return HttpResponseBadRequest('AddProduk instance not found')
    
    else:
        return HttpResponseBadRequest('GET method is not allowed')

def getVisitor(request):
    if request.session.get('sesi') == None:
        sesi = newVisitor(request)
    else:
        sesi = request.session['sesi']

    try:
        return Visitor.objects.get(id=sesi)

    except Visitor.DoesNotExist:
        sesi = newVisitor(request)
        return Visitor.objects.get(id=sesi)

def newVisitor(request):
    id = uuid.uuid4()
    request.session['sesi'] = str(id)
    try:
        Visitor.objects.create(id=id)
    except IntegrityError:
        Visitor.objects.get(id=id).delete()
        Visitor.objects.create(id=id)

    return id

keranjang/templates/keranjang/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block meta %}
<title>Checkout</title>
{% endblock meta %}

{% block content %}
<div class="content">
    <div class="container">
        <div class="row" style="text-align: center; background-color: #E0C387;">
            <div class="col" >
                <h1>Checkout</h1>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col">
                <h5>Berikut detail pengiriman:</h5>
                <div class="table-responsive-lg">
                    <table class="table table-striped">
                    <tr>
                        <th scope="col">Nama Lengkap</th>
                        <td>{{detail.nama}}</td>
                    </tr>
                    <tr>
                        <th scope="col">Nomor Telepon</th>
                        <td>{{detail.telpon}}</td>
                    </tr>
                    <tr>
                        <th scope="col">Email</th>
                        <td>{{detail.email}}</td>
                    </tr>
                    <tr>
                        <th scope="col">Alamat Lengkap</th>
                        <td>{{detail.alamat}}</td>
                    </tr>
                    <tr>
                        <th scope="col">Waktu Checkout</th>
                        <td>{{detail.waktu_checkout}}</td>
                    </tr>
                    <tr>
                        <th scope="col">Kurir</th>
                        <td>{{detail.kurir}}</td>
                    </tr>
                    <tr>
                        <th scope="col">Status</th>
                        <td><b>{{detail.status_pengiriman}} 
                            {% if detail.status_pengiriman.name == 'Menunggu Pembayaran' %}
                                ({{ detail.metode_pembayaran }})
                            {% endif %}</b> 
                        </td>
                    </tr>
                    <tr>
                        <th scope="col">Barang</th>
                        <td>
                            {% for p in detail.produkakandikirim.all %}
                            <a href="{% url 'detail:detailproduk' p.product.id %}">{{p.product.nama}}</a> ({{p.jumlah}})<br>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th scope="col">Total Harga</th>
                        <td>Rp {{detail.total_harga|intcomma}}</td>
                    </tr>
                    </table>
                </div>
            </div>
        </div>
        <hr>
        <!--
        <div class="row">
            <div class="col">
                <h5>Detail barang:</h5>
                <div class="table-responsive-lg">
                    <table class="table table-striped">
                        <thead>
                            <th>Nama Barang</th>
                            <th>Jumlah</th>
                            <th>Harga</th>
                        </thead>
                        <tbody>
                        {% for p in keranjang %}
                            <tr>
                                <td scope="col">{{ p.nama }}</td>
                                <td>x{{ p.jumlah }}</td>
                                <td>{{ p.totalharga }}</td>                            
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    -->
        <div class="row" style="text-align: center;">
            <div class="col">
                <h5>Kami akan segera memproses pesananmu :)</h5>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

keranjang/templates/keranjang/keranjang.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}

{% block meta %}
<title>Keranjang Belanjaan</title>
{% endblock meta %}

{% block content %}
<div class="content keranjang">
  <div class="container">
    <!--- SHOPPING CART --->    
      <div class="row cart">        
        <div class="col-md-8">
          <div class="cart d-flex flex-row align-items-center my-3" style="background-color: #E0C387;">
            <h4 class="hkeranjang">Shopping Cart</h4>
          </div>
          {% if produk|length > 0 %}
          {% for pd in produk %}     
          <div class="card mb-2 card-keranjang card-produk-keranjang" style="max-width:100%;">
            <div class="row no-gutters">
              <div class="col-md-4">
                <a href="{% url 'detail:detailproduk' pd.product.id %}">
                  <img src="{{ pd.product.foto }}" class="card-img img-card-keranjang" alt="#">
                </a>
              </div>
              <div class="col-md-4">
                <div class="card-body">
                  <a href="{% url 'detail:detailproduk' pd.product.id %}" style="color: black;">
                    <h5 class="card-title">{{ pd.product.nama|truncatechars:15 }}</h5>
                  </a>
                  <p class="card-text">Rp {{ pd.product.harga|intcomma }}</p>                  
                  <div class="form-inline card-text">
                    <small>
                      qty:&nbsp;
                    </small>
                    <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="detail_id" value="{{ pd.product.id }}">
                    <button formaction="{% url 'keranjang:decPOST' %}" type="submit" class="button1"{% if pd.jumlah == 1 %} disabled {% endif %}>-</button>
                    {{ pd.jumlah }}
                    <button formaction="{% url 'keranjang:incPOST' %}" type="submit" class="button1"{% if pd.jumlah == pd.product.stok %} disabled {% endif %} >+</button>
                    <button formaction="{% url 'keranjang:delPOST' %}" type="submit" class="button1">delete</button>
                    </form>
                  </div>
                </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <h5>Belum ada produk ditambahkan. <a href="{% url 'produk:listproduk' %}">Tambah Produk.</a> </h5>
            {% endif %}
            {% if produk|length > 0 %}
          <div class="cart d-flex flex-row align-items-center my-3" style="background-color: #E0C387;">
            <h4 class="hkeranjang">Shipping Details</h4>
          </div>
            <div class="container card card-keranjang" style="padding-top:10px">              
              <div class="myform form">
                
                <form action="/keranjang/checkout" method="POST">
                  {% csrf_token %}
                  <div>
                    {{ form }}
                  </div>
              </div>
            </div>
        </div>
        <div class="col-md-4">
          <div class="cart d-flex flex-row align-items-center my-3" style="background-color: #E0C387;">
            <h4 class="hkeranjang">Summary</h4></div>
            <div class="card p-4  card-keranjang">
              <div class="card-title">
                {% for pd in produk %}                     
                <p>{{ pd.jumlah }}x {{ pd.product.nama|truncatechars:20 }}
                  <span class="float-right subtotal1">
                    {% with jumlah=pd.jumlah harga=pd.product.harga %}
                    Rp {{ jumlah|mul:harga|intcomma }}
                    {% endwith %}
                  </span>
                </p>                      
                {% endfor %}
                <hr>
                <div>
                  <div class="float-left">Ongkos Kirim</div>:
                  <div id="totalPrice" class="float-right">-</div>
                </div>
                <div class="float-left">Total Harga:</div>
                  <div id="totalPrice" class="float-right">Rp {{ totalHarga|intcomma }}</div>
              </div>
              
                <hr>              
                    <input class="btn btn-primary btn-lg w-100 button2" type="submit" value="Checkout">      
                </form>
                {% endif %}
            </div>            
        </div>
      </div>
    </div>
</div>
{% endblock content %}